inherit: ["config.yml"]
bookname: LouisaVketReal2023Winter
# prt: ねこのしっぽ
texdocumentclass: ["review-jlreq", "media=ebook,paper=b5,fontsize=9pt,serial_pagination=true,hiddenfolio=shippo,startpage=2,tate,twoside,twocolumn,openany"]