inherit: ["config.yml"]
page_metric: A5
bookname: LouisaVketReal2023Winter
# prt: ねこのしっぽ
texdocumentclass: ["review-jlreq", "media=ebook,paper=a5,fontsize=8pt,serial_pagination=true,hiddenfolio=shippo,tate,twoside,twocolumn,openany"]